#!/bin/bash
source ~/.bashrc
source ~/catkin_ws/devel/setup.bash

while true; do
	clear
	printf "\nEnter Command:\n"
	printf "1: Start ZED and IMU\n"
	declare -i incommand
	read incommand


	#
	# ZED camera & UM7 IMU
	#
	if [ $incommand -eq 1 ]
	then

	printf "\nStarting UM7 IMU ROS node...\n"
	roslaunch um7 um7.launch & > /dev/null 2>&1
	
	sleep 3

	printf "\nStarting ZED...\n"
	roslaunch zed_wrapper zed_depth.launch & > /dev/null 2>&1
	sleep 5
	printf "\nDone!\n"
	
	else
		printf "whatever\n"
	fi

done
